"""
Initial revision, Clean DB. DB Model should only have an auto-incrememnting ID field
Revision ID: 323012e80841
Revises: 
Create Date: 2023-10-25 22:19:12.231204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "323012e80841"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("participant")
    op.add_column(
        "participant", sa.Column("id", sa.Integer, primary_key=True, index=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant", "id")
    op.drop_table("participant")
    # ### end Alembic commands ###
