"""empty message

Revision ID: 885054f5dc6b
Revises: b2cd3b252cb1
Create Date: 2024-02-29 16:52:41.238933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "885054f5dc6b"
down_revision: Union[str, None] = "b2cd3b252cb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sk_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interaction_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.String(), nullable=True),
        sa.Column("json_content", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sk_events_id"), "sk_events", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sk_events_id"), table_name="sk_events")
    op.drop_table("sk_events")
    # ### end Alembic commands ###
