"""
Creates event_outcome table

Revision ID: b2cd3b252cb1
Revises: b5c8e1cfcb42
Create Date: 2024-02-29 11:24:11.278296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2cd3b252cb1"
down_revision: Union[str, None] = "b5c8e1cfcb42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_outcome",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("company_id", sa.String(), nullable=True),
        sa.Column("connection_id", sa.String(), nullable=True),
        sa.Column("connector_id", sa.String(), nullable=True),
        sa.Column("flow_id", sa.String(), nullable=True),
        sa.Column("flow_version_id", sa.String(), nullable=True),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("interaction_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("node_description", sa.String(), nullable=True),
        sa.Column("node_title", sa.String(), nullable=True),
        sa.Column("outcome_description", sa.String(), nullable=True),
        sa.Column("outcome_status", sa.String(), nullable=True),
        sa.Column("outcome_type", sa.String(), nullable=True),
        sa.Column("should_continue_on_error", sa.String(), nullable=True),
        sa.Column("template_precompile", sa.String(), nullable=True),
        sa.Column("signal_id", sa.String(), nullable=True),
        sa.Column("transition_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_outcome_id"), "event_outcome", ["id"], unique=False)
    op.drop_table("response")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "response",
        sa.Column("interaction_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("response_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("survey_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("dist", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_event_outcome_id"), table_name="event_outcome")
    op.drop_table("event_outcome")
    # ### end Alembic commands ###
