"""Add all participant columns to the participant table

Revision ID: b5c8e1cfcb42
Revises: 323012e80841
Create Date: 2023-10-25 22:22:37.857141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5c8e1cfcb42"
down_revision: Union[str, None] = "323012e80841"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant", sa.Column("survey_id", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("response_id", sa.String(), nullable=True))

    op.add_column(
        "participant", sa.Column("rules_consent_id", sa.String(), nullable=True)
    )
    op.add_column("participant", sa.Column("time", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("date", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("ethnicity", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("race", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("gender", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("age", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("income", sa.String(), nullable=True))
    op.add_column("participant", sa.Column("skin_tone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant", "skin_tone")
    op.drop_column("participant", "income")
    op.drop_column("participant", "age")
    op.drop_column("participant", "gender")
    op.drop_column("participant", "race")
    op.drop_column("participant", "ethnicity")
    op.drop_column("participant", "date")
    op.drop_column("participant", "time")
    op.drop_column("participant", "rules_consent_id")
    op.drop_column("participant", "response_id")
    op.drop_column("participant", "survey_id")
    # ### end Alembic commands ###
